// Code generated by "stringer -type=HCSEventOptions -trimprefix=EventOption event.go"; DO NOT EDIT.

package computecore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventOptionNone-0]
	_ = x[EventOptionEnableOperationCallbacks-1]
}

const _HCSEventOptions_name = "NoneEnableOperationCallbacks"

var _HCSEventOptions_index = [...]uint8{0, 4, 28}

func (i HCSEventOptions) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_HCSEventOptions_index)-1 {
		return "HCSEventOptions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HCSEventOptions_name[_HCSEventOptions_index[idx]:_HCSEventOptions_index[idx+1]]
}
