// Code generated by "stringer -type=DriverType -linecomment"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriverTypeWindows-0]
	_ = x[DriverTypeWindowsLegacy-1]
	_ = x[DriverTypeLinux-2]
}

const _DriverType_name = "WindowsWindowsLegacyLinux"

var _DriverType_index = [...]uint8{0, 7, 20, 25}

func (i DriverType) String() string {
	if i < 0 || i >= DriverType(len(_DriverType_index)-1) {
		return "DriverType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DriverType_name[_DriverType_index[i]:_DriverType_index[i+1]]
}
