# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# See: https://sagiegurari.github.io/cargo-make/

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# override default args for built-in tasks

[tasks.format]
args = ["fmt", "--", "--emit=files"]

# check for copyright statements

[tasks.copyright]
script_runner = "powershell"
script_extension = "ps1"
script = '''
$ErrorActionPreference = 'Stop'
$VerbosePreference = 'Continue'

& "${env:CARGO_MAKE_WORKING_DIRECTORY}/scripts/Assert-CopyrightHeaders.ps1" @args -ErrorAction 'Stop' -Verbose
'''

# check command to be invoked by rust-analyser
[tasks.racheck]
extend = "check"
args = ["check", "--workspace", "--message-format=json", "--all-targets", "${@}"]

# default command

[tasks.validate]
description = "Format, lint, and then build."
dependencies = ["copyright", "format", "clippy", "build"]

[tasks.default]
alias = "validate"
