# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "init"
description = "Linux uVM init binary."
publish = false
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
anyhow.worspace = true

[lints]
workspace = true
